<a href="https://colab.research.google.com/github/seongkai102/Divisibility-rule-by-FSM/blob/main/%EC%BD%94%EB%93%9C%EC%97%85_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
matrix = []


for i in range(100):
  matrix.append([0 for j in range(100)])

N = int(input())
for k in range(N):
  x, y = map(int, input().split())
  for i in range(x, x + 10):
    for j in range(y, y + 10):
      matrix[i][j] = 1

myeonjuck = 0
for i in range(100):
  for j in range(100):
    if matrix[i][j] == 1:
      myeonjuck += 1
print(myeonjuck)

3
3 7
15 7
5 2
260


In [ ]:
a = int(input())
b = [input() for i in range(a)]

for i in range(a):
  if i+1 == a:
    print(b[i])
  else:
    print(f'{b[i]}\nAMOLED')

2
AMOLED
AMOLED
AMOLED
AMOLED
AMOLED


In [ ]:
a = int(input())

b = sorted([input() for _ in range(a)])
output_count = len(b) // a

for i in range(a):
    print(b[i])

2
def
avc
avc
def


In [ ]:
a = [input() for i in range(int(input()))]
b = 0
for i in a:
  if len(i) <= 3 or ('tap' in i or 'xocure' in i):
    b+=1
    print(i)

print("safe" if b <= 3 else ("warning" if b <= 6 else "danger"))

8
windows tap
hi
microsoft office 2013
xocure web player
xecure safe
goclean
alyac
von
windows tap
hi
xocure web player
von
warning


In [ ]:
w,h,n = map(int, input().split())

matr = [input() for i in range(n)]

new_m = ''
for i in matr:
  for j in range(h):
    for k in range(len(i)):
      a = i[k]*w
      new_m+=a
    new_m+='\n'

print(new_m)

3 3 5
**_**_**_**_**
_**_**_**_**_**
__**_**_**_**_**
___**_**_**_**_**
____**_**_**_**_**
******___******___******___******___******
******___******___******___******___******
******___******___******___******___******
___******___******___******___******___******
___******___******___******___******___******
___******___******___******___******___******
______******___******___******___******___******
______******___******___******___******___******
______******___******___******___******___******
_________******___******___******___******___******
_________******___******___******___******___******
_________******___******___******___******___******
____________******___******___******___******___******
____________******___******___******___******___******
____________******___******___******___******___******



In [ ]:
print(*(input().split(',')))

4,52,600,-5,0
4 52 600 -5 0


In [ ]:
a = input().split(';')

for i in a:
    b = i.split(',')
    for j in b:
        c = j.split()
        print(f'{c[0]}',end=' ')
    print()

In [ ]:
a, b = map(int, input().split())

print("tie" if a == b else "win" if (a == 0 and b == 1) or (a == 1 and b == 2) or (a == 2 and b == 0) else "lose")


In [ ]:
a,b = map(int, input().split())
c = a // b

if c > 9999:
  print('번호 초과 오류')
else:
  for i in range(1,c+1):
    print(f"F-{i:04}")


19 6
f-0001
f-0002
f-0003


In [ ]:
a,b,c = map(int, input().split())

for i in range(c, 0, -1):
  if a % i == 0 and b % i == 0 and c % i == 0 :
    print(i)
    break

10 20 30
10


In [ ]:
a = sum([ int(i) for i in input() ])
print('Bad' if a % 7 == 4 else 'Good')

1234567890
Good


In [ ]:
a = int(input())
b = [int(input()) for i in range(a)]
c = sorted(b, reverse=True)

for i in b:
  print(c.index(i)+1)

3
100
90
90
1
2
2


In [ ]:
a,b = map(int, input().split())

print(f'+{"-"*(a-2)}+')
for i in range(b-2):
  print(f"|{' '*(a-2)}|")
print(f'+{"-"*(a-2)}+')

3 3
+-+
| |
+-+


In [ ]:
mat = [list(map(int, input().split())) for i in range(5)]

dir = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]

cnt = []

for x in range(5):
  for y in range(5):
    c = []
    c.append(mat[x][y])
    for dx, dy in dir:
      nx, ny = x + dx, y + dy
      if 0 <= nx < 5 and 0 <= ny < 5:
        c.append(mat[nx][ny])
    cnt.append(sum(c))

print(max(cnt))

1 1 1 1 1 
1 1 2 2 2 
1 1 2 2 2
1 1 2 2 2
1 1 1 1 1
18
[4, 7, 8, 9, 6, 6, 11, 13, 15, 10, 6, 12, 15, 18, 12, 6, 11, 13, 15, 10, 4, 7, 8, 9, 6]


In [ ]:
n = int(input())

cnt = 0
for a in range(1, n):
    for b in range(a, n):
        c = n - (a + b)
        if c < b:
            break
        if b + a > c:
            print(f"{a} {b} {c}")
            cnt += 1
if cnt == 0:
    print("-1")

9
1 4 4
2 3 4
3 3 3


In [ ]:
for s in range(10):
    for o in range(10):
        for t in range(10):
            if len(set([s, o, t])) != 3:
                continue

            so = 10 * s + o
            too = 100 * t + 10 * o + o

            if so + so == too:
                print(f"{so}+{so}={too}")



50 + 50 = 100


In [ ]:
a = list(map(int, input().split()))
print(*a[::-1])

5 7 2
2 7 5


In [ ]:
b = list(map(int, input().split()))
a = ''.join(map(str, b))
print( f'{a} {a}' if int(b[1])% 2 == 0 else a)

2 2 14
2214 2214


In [ ]:
a = int(input())

hout = a // 3600
remaining_after_hours = a % 3600
mit = remaining_after_hours // 60
sec = remaining_after_hours % 60

print(hout, mit, sec)

3602
1 0 2


In [ ]:
a = input()
b = '20'+a[:2] if int(a[7]) > 2 else '19'+a[:2]
c =  'M' if int(a[7]) % 2 != 0 else 'F'
print(2013 - int(b) ,c)

020111 4421234 
11 F


In [ ]:
a = input()
b = a.count('3') + a.count('6') + a.count('9')
print(a if b ==0 else 'K' if b==1 else 'KK' if b==2 else 'KKK')

93
KK


In [ ]:
a = list(map(int, input().split()))
b = f'{sum(a)/len(a):.01f}'
c,d=0,0
for i in a:
  if i >= float(b):
    c+=1
  else:
    d+=1

print(f'{b}\n{c} {d}')

0 0 0 0 0 0 0 0 0 0
0.0
10 0


In [ ]:
z = input()
a = list(map(int, input().split()))
b = sorted(a, reverse=True)

for i in a:
  print(i,b.index(i)+1)

97 65 84 84 91
97 65 84 84 91
97 1
65 5
84 3
84 3
91 2


In [ ]:
a = input()
print(*sorted(list(map(int, input().split())), reverse=True))

7
51 44 81 1 9 12 25
81 51 44 25 12 9 1


In [ ]:
#1711
x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())
x3, y3 = map(int, input().split())

max_x = max(x1, x2)
max_y = max(y1, y2)

matrix = [[0] * (max_y + 1) for _ in range(max_x + 1)]

# 사각형 그리기
for x in range(min(x1, x2), max(x1, x2) + 1):
    for y in range(min(y1, y2), max(y1, y2) + 1):
        matrix[x][y] = 1

print('비충돌' if x3 > max_x or y3 > max_y else '충돌' if matrix[x3][y3] == 1  else '비충돌')

10 3
15 8
1 1
비충돌


In [ ]:
a,b,c = map(int, input().split())
print(*[i for i in range(a,c+1,b-a)])

1 3 40
1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39


In [ ]:
a, b = map(int, input().split())

x,y = 0,0
for i in range(a,b+1):
  if i % 3 == 0 and i % 4 == 0:
    pass
  elif i % 3 == 0:
    x+=i
  elif i % 4 == 0:
    y+=i

print(x-y)

3 16
5


In [ ]:
print(input()[::-1])

123456
654321


In [ ]:
from math import gcd

a, b = map(int, input().split())
g = gcd(a, b)
print(a // g, b // g)

2802 9628
1401 4814


In [ ]:
a, b = map(int, input().split())

c = 0
for i in range(1, a):
  if i % 2 == 0:
    c+=30
  else:
    c+=31


print(306-c+b)

10 29
60


In [ ]:
a, b = map(int, input().split())

c = 0
for i in range(1, a):
    if i % 2 == 0:
        c += 30
    else:
        c += 31

print(305 - (c + (b - 1))-1)


10 29
1


305

In [ ]:
a = input()
C = int(a[a.find('C')+1:a.find('H')]) if a[a.find('C')+1] != 'H' else 1
H = int(a[a.find('H') + 1:]) if a.find('H') != -1 and a[a.find('H') + 1:].isdigit() else 1
print(C*12+H*1)


C12H12
156


In [ ]:
a = int(input())
b = [list(map(int, input().split())) for i in range(a)]

c = True
for i in range(a):
  if min(b[i][0:3]) != b[i][-1]:
    print(i+1, min(b[i][0:3]))
    c = False
    break

if c:
  print(-1)

3
3 5 8 3
3 9 8 8
8 3 9 3
2 3


In [ ]:
import math
z = input()
x1, y1 = map(int, input().split())

x2, y2 = map(int, input().split())

x3, y3 = map(int, input().split())

distance1 = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
distance2 = math.sqrt((x3 - x2)**2 + (y3 - y2)**2)
print(f"{distance1+distance2:.2f}")



In [ ]:
import math
a = int(input())
b = [list(map(int, input().split())) for _ in range(a)]

distance = 0
for i in range(len(b)-1):
  distance += math.sqrt((b[i][0] - b[i+1][0])**2 + (b[i][1] - b[i+1][1])**2)

print(f'{distance:.02f}')


3
0 0
3 4
6 0
10.00


In [ ]:
print('special characters')
print('[\\n,\\",\\\\] is very important.')

special characters
[\n,\",\\] is very important.


In [ ]:
a, b = map(int, input().split())
print(f'{a/b:.1f}\n{a//b}\n{a**b}')

4 3
1.3
1
64


In [ ]:
print('IOI is the International Olympiad in Informatics.' if input() == 'IOI' else 'I don\'t care.')

IOI
IOI is the International Olympiad in Informatics.


In [ ]:
print('welcome! ' +  input())

anaki
welcome! anaki


In [ ]:
a = int(input())

date = a// 86400
hout = (a-86400*date) // 3600
remaining_after_hours = a % 3600
mit = remaining_after_hours // 60
sec = remaining_after_hours % 60

print(date ,hout, mit, sec)

	 302090
3 11 54 50


In [ ]:
print(len(input()))

black sheep wall
16


In [ ]:
print(input()[::-1])

KAIST
TSIAK


In [ ]:
b = [input() for i in range(int(input()))]
for i in b:
  print(i[::-1])

3
taehyeon
hyeonmin
sera
noeyheat
nimnoeyh
ares


In [ ]:
a = list(map(int, input().split()))
print(min(a), max(a))

9999999999999999999999999 9999999999999999999999998
9999999999999999999999998 9999999999999999999999999


In [ ]:
a =  {
    "dib": "Paint.Picture",
    "doc": "Word.Document.8",
    "docx": "Word.Document.12",
    "htm": "htmfile",
    "html": "htmlfile",
    "hwp": "Hwp.Document.96",
    "hwpx": "Hwp.Document.hwpx.96",
    "hwt": "Hwp.Document.hwt.96",
    "jpe": "jpegfile",
    "jpeg": "jpegfile",
    "jpg": "jpegfile",
    "ppt": "PowerPoint.Show.8",
    "pptx": "PowerPoint.Show.12",
    "pptxml": "powerpointxmlfile"
}

print(a[input().split('.')[-1]])

codeup.pptx
PowerPoint.Show.12


In [ ]:
a = input()
b = {a[i]: i for i in range(len(a))}
c = input().split()
for i in c:
  for j in range(len(i)):
    print(f'{b[i[j]]}', end = '')
  print('', end = ' ')


lohcgpdabk
lol abk abk
010 789 789 

In [ ]:
a = sorted(
    [list(map(int, input().split())) for _ in range(int(input()))],
    key=lambda x: x[0]
)
for i in a:
  print(*i)

3
2 10
3 20
1 30
1 30
2 10
3 20


In [ ]:
def ubs(n, hs = 1):
  if n == 1:
    return hs
  elif n % 2 == 0:
    hs += 1
    return ubs(n//2, hs)
  else:
    hs += 1
    return ubs((3*n+1), hs)

a, b=map(int, input().split())

c = []
for i in range(a, b+1):
  c.append((i, ubs(i)))

print(*max(c, key = lambda x: x[1]))


1 10
9 20


In [ ]:
def h():
    print("Hello, world!", end=" ")

def q(code):
    print(code, end=" ")

def b():
    for i in range(99, 2, -1):
        print(f"{i} bottles of beer on the wall, {i} bottles of beer.")
        print(f"Take one down and pass it around, {i-1} bottles of beer on the wall.")
    print("2 bottles of beer on the wall, 2 bottles of beer.")
    print("Take one down and pass it around, 1 bottle of beer on the wall.")
    print("1 bottle of beer on the wall, 1 bottle of beer.")
    print("Take one down and pass it around, no more bottles of beer on the wall.")
    print("No more bottles of beer on the wall, no more bottles of beer.")
    print("Go to the store and buy some more, 99 bottles of beer on the wall.")

def main():
    code = input()
    for char in code:
        if char == 'H':
            h()
        if char == 'Q':
            q(code)
        if char == '9':
            b()

if __name__ == "__main__":
    main()


In [ ]:
a = input()
b,c = map(int, input().split())
print(a[b-1:c])

abcde
1 3
abc


In [ ]:
def a(a):
  return '*'*a

print(a(int(input())))

3
***


In [ ]:
def print_numbers(n,i=1):
    if i > n:
        return
    else:
        print(i, end = ' ')
        return print_numbers(n, i+1)

print_numbers(int(input()))

10


55

In [ ]:
def print_numbers(n,i=1,b=[]):
    if i > n:
        return sum(b)
    else:
        b.append(i)
        return print_numbers(n, i+1, b)

print(print_numbers(int(input())))

10
55


In [ ]:
print(sum(map(int, input())))

1234
10


In [ ]:
def fib(n):
    if n == 0:
        return 0
    elif n == 1 or n == 2:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)

print(fib(int(input())))

6
8


In [ ]:
def count_ways(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    elif n == 3:
        return 4
    else:
        return count_ways(n - 3) + count_ways(n - 2) + count_ways(n - 1)

n = int(input())
print(count_ways(n))


3
4


In [ ]:
import math
a,b = map(int, input().split())
print(math.comb(a,b))

In [ ]:
def pascal(n, k):
    if k == 0 or k == n:
        return 1
    return pascal(n-1, k-1) + pascal(n-1, k)

n, k = map(int, input().split())
print(pascal(n-1, k-1))


5 3
6


In [ ]:
def star(n,b=1):
  print('*'*b)
  if b == n:
    return ''
  return star(n,b+1)


print(star(int(input())))

5
*
**
***
****
*****



In [ ]:
def sp(n, b=[1]):

  print(*b)
  if len(b) == n:
    return ''
  b.append(b[-1]+1)
  return sp(n, b)

print(sp(int(input())))

5
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5



In [ ]:
#1861
def pascal_triangle(n, row=0, col=0):
    if row == n:
        return ''
    if col > row:
        print()
        return pascal_triangle(n, row + 1, 0)
    print(1 if col == 0 or col == row else pascal_triangle_value(row, col), end=" ")
    return pascal_triangle(n, row, col + 1)

def pascal_triangle_value(row, col):
    if col == 0 or col == row:
        return 1
    return pascal_triangle_value(row - 1, col - 1) + pascal_triangle_value(row - 1, col)

num_rows = int(input())
print(pascal_triangle(num_rows))


5
1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 



In [ ]:
#1862
MOD = 1000000007

def fibonacci(n, memo={1: 1, 2: 1}):
    if n in memo: #종료 코드
        return memo[n]
    memo[n] = (fibonacci(n - 1, memo) + fibonacci(n - 2, memo)) % MOD
    # print(f"n = {n}, memo = {memo}")
    return memo[n] #중간 상태 저장 (if문이 실행되기 전까지)

n = int(input())
print(fibonacci(n))


67
569898238


In [ ]:
def hs(a,b=1,c=[]):
  if b>a:
    return c
  c.append(b)
  return hs(a,b+1,c)

a = int(input())
print(sum(hs(a)))

100
5050


In [ ]:
import sys

sys.setrecursionlimit(100000)

def hs(a, b=0):
    if a == 0:
        return b
    return hs(a - 1, b + a)

a = int(input())
print(hs(a))


In [ ]:
def fac(n):
  if n ==0:
    return 1
  return n*fac(n-1)

print(fac(int(input())))

5
120


In [ ]:
def fib(n):
    if n == 0:
        return 0
    elif n == 1 or n == 2:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)

print(fib(int(input())))

7
13


In [ ]:
from functools import lru_cache

@lru_cache(None)
def fib(n):
    if n == 0:
        return 0
    elif n == 1 or n == 2:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)

print(fib(int(input())) % 10009)


151
3081


In [ ]:
import sys
sys.setrecursionlimit(100000)

def ss(base, exponent):
    if exponent == 0:
        return 1
    if exponent % 2 == 0:
        half_result = ss(base, exponent // 2)
        return half_result * half_result
    else:
        return base * ss(base, exponent - 1)

base, exponent = map(int, input().split())
print(ss(base, exponent))


In [ ]:
print(int(input()[::-1]))

1200


21

In [ ]:
print(bin(int(input()))[2:])

7
111


In [ ]:
def to_base_recursive(n, k):
    return (to_base_recursive(n // k, k) if n >= k else '') + "0123456789ABCDEF"[n % k]

n, k = map(int, input().split())
print(to_base_recursive(n, k))

14 16
E


In [ ]:
def hc(a, hs=1):
    return hs if a == 1 else hc(3*a + 1 if a % 2 else a // 2, hs + 1)

a = int(input())
print(hc(a))

21
8


In [ ]:
import math
a,b = map(int, input().split())
print(math.comb(a,b))

TypeError: 'str' object is not callable

In [ ]:
def hc(a, hs=[]):
  hs.append(a)
  return hs if a == 1 else hc(3*a + 1 if a % 2 else a // 2, hs)

a = int(input())
print(hc(a))

5
[5, 16, 8, 4, 2, 1]


In [ ]:
def hc(a, hs=[]):
  hs.append(a)
  return hs if a == 1 else hc(3*a + 1 if a % 2 else a // 2, hs)

def pp(a = hc(int(input())), hs=0):

    if len(a) == hs:
        return ''
    print(a[-(hs + 1)])
    return pp(a, hs + 1)

print(pp())

TypeError: 'str' object is not callable

In [ ]:
import sys
from functools import lru_cache

@lru_cache(None)
def SuperSum(k, n):
    if k == 0:
        return n
    return sum(SuperSum(k - 1, i) for i in range(1, n + 1))

#input = sys.stdin.read()
data = input.split()

i = 0
while i < len(data):
    k = int(data[i])
    n = int(data[i + 1])
    print(SuperSum(k, n))
    i += 2

In [ ]:
def find_lca(a, b):
    if a == b:
        return a
    if a > b:
        return find_lca(a // 2, b)
    return find_lca(a, b // 2)


a, b = map(int, input().split())

print(find_lca(a, b))

In [ ]:
def find_lca(a, b, hs=0):
    if a == b:
        return hs
    if a > b:
        return find_lca(a // 2, b,hs+1)
    return find_lca(a, b // 2,hs+1)


a, b = map(int, input().split())

print(find_lca(a, b))

3 4
3


In [ ]:
def see(a,b=1):
  print('*'*b)
  if b == a:
    return ''
  return see(a,b+1)

print(see(int(input())))

3
*
**
***



In [ ]:
def see(a):
  print('*'*a)
  if a == 1:
    return ''
  return see(a-1)

print(see(int(input())))

3
***
**
*



In [ ]:
def L(n):
  line = 1+(n*(n+1)//2)
  return line

print(L(2)%137)

4


In [ ]:
n = int(input())
print(1+(n*(n+1)//2)%137)

3
7


In [ ]:
(700+198)+((700+198))*(10/100)
a = [int(input()) for i in range(3)]
b = [int(input()) for i in range(2)]

987.8

In [36]:
#1373

import sys

def mn(m, n, p):
    if m < n:
        m, n = n, m

    remains = [0] * 2400
    c = 1

    for i in range(m + n, m, -1):
        k = i
        for j in range(2, k + 1):
            while k % j == 0:
                k //= j
                remains[j] += 1

        if i - m > 0:
            k = i - m
            for j in range(2, k + 1):
                while k % j == 0:
                    k //= j
                    remains[j] -= 1

    if p != 0:
        for i in range(2400):
            if remains[i] != 0:
                j = remains[i]
                while j > 0:
                    c *= i
                    c %= p
                    j -= 1
    else:
        for i in range(2400):
            if remains[i] != 0:
                j = remains[i]
                while j > 0:
                    c *= i
                    j -= 1

    return c

n, m, k, p = map(int, input().split())
m = abs(m)
n = abs(n)

if m < n:
    m, n = n, m

if p != 0:
    if m == 1 and n == 1:
        print(4, 4 % p)
        sys.exit()
    if m == 2 and n == 1:
        if k == 0:
            print(3, 1 % p)
        else:
            print(5, 8 % p)
        sys.exit()
    if n == 0:
        if m == 0:
            if k == 0:
                print(4, 8 % p)
            else:
                print(6, 24 % p)
        else:
            if k:
                if m == 3:
                    print(5, 10 % p)
                elif m == 2:
                    print(4, 2 % p)
                elif m == 1:
                    print(5, 10 % p)
                else:
                    print(m + 2, (((m * (m - 1) // 2) + m) * 2) % p)
            else:
                print(m + 2, (((m * (m - 1) // 2) + m) * 2) % p)
        sys.exit()
    if k:
        if m == n:
            print(m + n, (mn(m, n, p) - 4 + p) % p)
        elif abs(m - n) == 1:
            print(m + n, (mn(m, n, p) - 3 + p) % p)
        else:
            print(m + n, (mn(m, n, p) - 2 + p) % p)
    else:
        print(m + n, (mn(m, n, p) - 2 + p) % p)
else:
    if m == 1 and n == 1:
        print(4, 4)
        sys.exit()
    if m == 2 and n == 1:
        if k == 0:
            print(3, 1)
        else:
            print(5, 8)
        sys.exit()
    if n == 0:
        if m == 0:
            if k == 0:
                print(4, 8)
            else:
                print(6, 24)
        else:
            if k:
                if m == 3:
                    print(5, 10)
                elif m == 2:
                    print(4, 2)
                elif m == 1:
                    print(5, 10)
                else:
                    print(m + 2, ((m * (m - 1) // 2) + m) * 2)
            else:
                print(m + 2, ((m * (m - 1) // 2) + m) * 2)
        sys.exit()
    if k:
        if m == n:
            print(m + n, mn(m, n, p) - 4)
        elif abs(m - n) == 1:
            print(m + n, mn(m, n, p) - 3)
        else:
            print(m + n, mn(m, n, p) - 2)
    else:
        print(m + n, mn(m, n, p) - 2)


3 0 1 0
5 10
3 -1


In [ ]:
#2001
a = [int(input()) for i in range(3)]
b = [int(input()) for i in range(2)]

c = []
for i in b:
  for j in a:
    c.append((i + j) + ((i + j) * (10 / 100)))

print(f'{min(c):.01f}')

800
700
900
198
330
987.8


In [ ]:
#2002
k = int(input())
a = input()
b = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'I': 9, 'J': 10, 'K': 11, 'L': 12, 'M': 13, 'N': 14, 'O': 15, 'P': 16, 'Q': 17, 'R': 18, 'S': 19, 'T': 20, 'U': 21, 'V': 22, 'W': 23, 'X': 24, 'Y': 25, 'Z': 26}

def get_key_from_value(dictionary, value):
    for key in dictionary:
        if dictionary[key] == value:
            return key
    return None

for i in range(1,len(a)+1):
  s = 3*i+k
  next = (b[a[i-1]] - s)+26 if b[a[i-1]] - s < 1 else b[a[i-1]] - s
  print(get_key_from_value(b, next),end = '')

In [ ]:
a = ['*x*', ' xx','* *']
b = int(input())
c = []
for i in a:
  for j in range(b):
    print(f'{i[0]*b}{i[1]*b}{i[2]*b}')

3
***xxx***
***xxx***
***xxx***
   xxxxxx
   xxxxxx
   xxxxxx
***   ***
***   ***
***   ***


In [ ]:
#2007
a = int(input())
b = list(map(int, input().split()))

srt, n_srt = False, False
for i in range(len(b)-1):
  if b[i] < b[i+1]:
    srt = True
  elif b [i] > b[i+1]:
    n_srt = True


print('섞임' if srt == True and n_srt == True else '오름차순' if srt else '내림차순')
srt,n_srt

1
2992 444 123 111 74 33333
섞임


(True, True)

In [ ]:
#2008
a = int(input())
b = list(map(int, input().split()))

srt, n_srt = False, False
for i in range(len(b)-1):
  if b[i] < b[i+1]:
    srt = True
  elif b [i] > b[i+1]:
    n_srt = True
  else:
    pass

print('섞임' if srt == True and n_srt == True or len(set(b)) == 1 else '오름차순' if srt else '내림차순')

3
4 4 4
섞임


In [ ]:
#2004
# 입력
rows, cols = map(int, input().split())
cell_rows, cell_cols = map(int, input().split())

# 체크보드 생성
for i in range(rows):
    for k in range(cell_rows):
        line = []
        for j in range(cols):
            if (i + j) % 2 == 0:
                line.append('X' * cell_cols)
            else:
                line.append('.' * cell_cols)
        print(''.join(line))


In [ ]:
#2005

n = int(input())
a = list(map(int, input().split()))
m = int(input())

is_residue_system = True

for i in range(n):
    for j in range(i + 1, n):
        if abs(a[i] - a[j]) % m == 0:
            print('no')
            is_residue_system = False
            break
    if not is_residue_system:
        break

if is_residue_system:
    print('yes')

7
22 5 648 40 334 246 97 
9
no


In [ ]:
#2006
a, b, c, d, s = [int(input()) for _ in range(5)]

def dist(a, b, s):
    q, r = divmod(s, a + b)
    res = q * (a - b) + min(r, a) - (r - a if r > a else 0)
    return res

nd = dist(a, b, s)
bd = dist(c, d, s)

print("Tied" if nd == bd else "Nikky" if nd > bd else "Byron")


4
2
5
3
12
Byron


In [ ]:
a, b = map(int, input().split())

ame = 0

while a >= b:
    new_ame = a // b
    ame += new_ame
    a = a % b + new_ame

print(ame)

10 3
4


In [ ]:
b, n = map(int, input().split())

a = round(b ** (1 / n))

candidates = [a, a - 1, a + 1]

print(min(candidates, key=lambda x: abs(b - x ** n)))

1000000 9
4
4


In [ ]:
for star in range(1, 10):
    for tri in range(0, 10):
        for sqa in range(0, 10):
            left = star * 100 + tri * 10 + sqa
            right = star * 10 + tri
            if left - right == sqa * 10 + sqa:
                print(f"{left}-{right}={sqa * 10 + sqa}")


109 - 10 = 99


In [ ]:
#2016
a = int(input()) // 3
b = input()[::-1]

c = [b[3*i:3*i+3] for i in range(a)]
if b[3*a:]:
    c.append(b[3*a:])

d = ','.join([i[::-1] for i in c[::-1]])

print(d)


8
12421421
12,421,421


In [ ]:
#2020
a = input()
symbol = {'I':1,'V':5,'X':10,"L":50,'C':100, 'D':500, 'M':1000}

num,mjy  = [],[]
for i in a:
  try:
    num.append(int(i))
  except:
    mjy.append(i)

b = 0
for i in range(len(mjy)):
    if i == len(mjy) - 1:
        b += symbol[mjy[i]] * num[i]
    elif symbol[mjy[i]] >= symbol[mjy[i + 1]]:
        b += symbol[mjy[i]] * num[i]
    else:
        b -= symbol[mjy[i]] * num[i]

print(b)

3M1D2C
3700


In [ ]:
#2043
word = input()

fst = word[0].upper()

map = {
    'b': '1', 'f': '1', 'p': '1', 'v': '1',
    'c': '2', 'g': '2', 'j': '2', 'k': '2', 'q': '2', 's': '2', 'x': '2', 'z': '2',
    'd': '3', 't': '3',
    'l': '4',
    'm': '5', 'n': '5',
    'r': '6'
}

enc = []
prev = None
for ch in word[1:].lower():
    if ch in "aehiouwy":
        prev = None
        continue
    dig = map.get(ch, '')
    if dig != prev or prev is None:
        enc.append(dig)
        prev = dig

res = fst + ''.join(enc)

print(res[:4].ljust(4, '0'))

Codeup
C310


In [ ]:
a, b = map(int, input().split())

for i in range(a, b+1):
  count = sum(1 for digit in str(i) if digit in '369')
  if count > 0:
      print('K' * count)
  else:
      print(i)

3 16
K
4
5
K
7
8
K
10
11
12
K
14
15
K


In [ ]:
a, b = map(int, input().split())
c = sum([1 for i in range(a, b+1) for j in range(len(str(i))) if str(i)[j] == '1'])
print(c)

9 13
5


In [ ]:
from itertools import groupby

def look_and_say(sequence):
    return ''.join(str(len(list(group))) + digit for digit, group in groupby(sequence))

def look_and_say_range(a, b):
    sequence = "1"
    for i in range(1, b + 1):
        if i >= a:
            reversed_sequence = ' '.join(sequence[::-1])
            print(reversed_sequence)
        sequence = look_and_say(sequence)
    return ''

a,b = map(int, input().split())
print(look_and_say_range(a, b))


1 6
1
1 1
1 2
1 1 2 1
1 2 2 1 1 1
1 1 2 2 1 3



In [ ]:
#2017
def f(n, k):
    if n == 0:
        return
    f(n // k, k)
    if n % k < 10:
        print(a[n % k], end='')
    else:
        print(a[n % k], end='')

a = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
     'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
     'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
     'U', 'V', 'W', 'X', 'Y', 'Z']

n, k = map(int, input().split())
if n == 0:
    print("0")
else:
    f(n, k)

In [ ]:
#2019
import math

a,b,c = map(int, input().split())

d = b**2 - 4*a*c

if d > 0:
    x1 = (-b + math.sqrt(d)) / (2*a)
    x2 = (-b - math.sqrt(d)) / (2*a)
    print(f"{x1:.02f}\n{x2:.02f}")
elif d == 0:
    x = -b / (2*a)
    print(f'{x:.02f}')
else:
    real_part = -b / (2*a)
    imaginary_part = math.sqrt(-d) / (2*a)
    print(f"{real_part:.02f}+{imaginary_part*-1 if imaginary_part < 0 else imaginary_part:.02f}i\n{real_part:.02f}-{imaginary_part*-1 if imaginary_part < 0 else imaginary_part:.02f}i")

-9 -8 -4
-0.44+0.50i
-0.44-0.50i


In [ ]:
#2025

a = input().split('/')
c = a[1]+a[2]
b = []

a0_list = list(a[0])
e = True
try:
  for i in c:
    if i in a[0]:
      b.append(i)
      a0_list[a0_list.index(i)] = ''
except:
  print('no')
  e = False

if e and len(b) == 4:
  print('yes')
elif len(b) < 4 and e:
  print('no')

1001/10/11
no


In [58]:
#2035
a = int(input())
b = list(map(int, input().split()))

c = 0

if b[0] == 0 and (a == 1 or b[1] == 0):
    c += 1

for i in range(1,a-1):
  if b[i] == 1:
    pass
  elif b[i-1] == 0 and  b[i] == 0 and  b[i+1] == 0:
    c+=1

if b[-1] == 0 and (a == 1 or b[-2] == 0):
    c += 1

print(c if a != 1 else 1 if b[0] == 0 else 0)

1 
1
0


In [ ]:
#2037

a = int(input())

b = set()
i = a
while True:
  if i // a == 1:
    b.add(i)
  else:
    break
  i+=1

print(b)


8
{8, 9, 10, 11, 12, 13, 14, 15}


In [ ]:
#2055

def f(n):
    divisors = set()

    for i in range(1, int(n**0.5) + 1):
        if n % i == 0:
            divisors.add(i)
            divisors.add(n // i)

    return sorted(divisors)

a,b = map(int, input().split())
print(*sorted(set(f(a)+f(b))))

61 4
1 2 4 61


In [ ]:
#2083
a, b = map(int, input().split())
c = list(map(int, input().split()))

print(c.index(b)+1 if b in c else -1)

left, right = 0, len(c) - 1
position = -1

while left <= right:
    mid = (left + right) // 2
    if c[mid] >= b:
        position = mid + 1
        right = mid - 1
    else:
        left = mid + 1

print(position)

3 7
2 3 4
-1


In [ ]:
#2364
n = int(input())
print((n + 4) // 5 , 150000*(n//5))

6
2 150000


In [ ]:
n = int(input()) * 10
c = 0
for i in [25, 15, 10]:
    c += n // i
    n %= i
print(c+1 if n > 0 else c)

In [ ]:
#2379
n = 20240
c = 0
for i in [25, 15, 10]:
    c += n // i
    n %= i
print(c+1 if n > 0 else c)

810


In [68]:
#2441

a = int(input())
b = [input().split(',')[1] for i in range(a)]

print(b.count('M'),b.count('F'))

2
Addison,F,18,Sharon,Kimberly,Joshua
Addison,F,18,Sharon,Kimberly,Joshua
0 2


In [ ]:
#2602
a = [list(map(int, input().split())) for i in range(3)]

for i in range(3):
  print(*a[i], sum(a[i]))
  a[i].append(sum(a[i]))

for i in range(4):
  b = 0
  for j in range(3):
    b+=a[j][i]
  print(b, end = ' ')


93 94 87 
82 75 91 
78 89 92 
93 94 87 274
82 75 91 248
78 89 92 259
253 258 270 781 

In [23]:
#2603
a = [i//10 for i in list(map(int, input().split()))]
b = [[' ']*10 for i in range(10)]

for i in range(10):
  for j in range(9,(9-a[i]),-1):
    b[j][i] = '#'

for i in b:
  print(*i)

25 20 30 40 56 79 8 15 90 52
                   
                #  
                #  
          #     #  
          #     #  
        # #     # #
      # # #     # #
    # # # #     # #
# # # # # #     # #
# # # # # #   # # #


In [ ]:
#2605
def dfs(board, visited, x, y, color):
    dx = [-1, 1, 0, 0]
    dy = [0, 0, -1, 1]

    stack = [(x, y)]
    visited[x][y] = True
    count = 1

    while stack:
        cx, cy = stack.pop()

        for i in range(4):
            nx, ny = cx + dx[i], cy + dy[i]

            if 0 <= nx < 7 and 0 <= ny < 7 and not visited[nx][ny]:
                if board[nx][ny] == color:
                    visited[nx][ny] = True
                    stack.append((nx, ny))
                    count += 1

    return count

def count_touchable_areas(board):
    visited = [[False] * 7 for _ in range(7)]
    touchable_areas_count = 0

    for i in range(7):
        for j in range(7):
            if not visited[i][j]:
                connected_cells_count = dfs(board, visited, i, j, board[i][j])
                if connected_cells_count >= 3:
                    touchable_areas_count += 1

    return touchable_areas_count

board = [list(map(int, input().split())) for _ in range(7)]

print(count_touchable_areas(board))

2 1 5 1 1 3 4
2 1 5 1 3 5 3
2 3 4 5 2 2 4
4 4 3 2 3 1 3
4 3 5 3 1 4 3
5 4 4 3 3 5 5
2 1 3 5 1 1 2
34


In [ ]:
#2607 에라토스테네스의 체 알고리즘
def sieve_of_eratosthenes(limit):
    is_prime = [True] * (limit + 1)
    p = 2
    while (p * p <= limit):
        if is_prime[p]:
            for i in range(p * p, limit + 1, p):
                is_prime[i] = False
        p += 1
    return is_prime

def find_twin_primes(a, b):
    primes = sieve_of_eratosthenes(b)
    twin_primes = []

    for i in range(a, b - 1):
        if primes[i] and primes[i + 2]:
            twin_primes.append((i, i + 2))

    return twin_primes

a, b = map(int, input().split())

twin_primes = find_twin_primes(a, b)

for tp in twin_primes:
    print(tp[0], tp[1])

2 20
3 5
5 7
11 13
17 19


In [ ]:
#2608 백트래킹
def generate_votes(n, current_vote=""):
    if len(current_vote) == n:
        print(current_vote)
        return

    generate_votes(n, current_vote + "O")

    generate_votes(n, current_vote + "X")


n = int(input())
generate_votes(n)

In [ ]:
#2621
a =int(input())
print(sum([i for i in range(1,a+1) if a % i ==0]))

10
18


In [ ]:
#2622
a = input()
b = list(enumerate(map(int,input().split())))
c , d = min(b,key = lambda x : x [1]), max(b,key = lambda x : x [1])

print(d[0]+1,':',d[1])
print(c[0]+1,':',c[1])

3
100 36 55
2 36
1 100


In [ ]:
#2624
limit = int(input())

is_prime = [True] * (limit + 1)
p = 2
while (p * p <= limit):
    if is_prime[p]:
        for i in range(p * p, limit + 1, p):
            is_prime[i] = False
    p += 1

primes = is_prime
twin_primes = []

for i in range(2, limit+1):
    if primes[i]:
        twin_primes.append(i)

print(sum(twin_primes))

10
17


In [ ]:
#2628

def is_between(x, a, b):
    if a < b:
        return a < x < b
    else:
        return a < x or x < b

A, B = map(int, input().split())
C, D = map(int, input().split())

e = False
if (is_between(C, A, B) != is_between(D, A, B)) and (is_between(A, C, D) != is_between(B, C, D)):
    e = True

print('cross' if e else 'not cross')


12 53
99 45
cross


In [ ]:
#2632
def count_ways(n, current):
    if current > n:
        return 0

    if current == n: #만약 더한게 n과 같다면 +1
        return 1

    ways = 0

    ways += count_ways(n, current + 1) #경우의수

    ways += count_ways(n, current + 2) # 경우의수 1과 2로 만들수 있는 n

    return ways


n = int(input())
result = count_ways(n, 0)
print(result)

3
3


In [ ]:
#2640
a,b = map(int, input().split())
print(pow(a,b,1000000007))

4 2
16


In [ ]:
#2641 백트래킹(Backtracking)은 가능한 모든 해를 탐색하는 알고리즘
def count_ways(n, current, consecutive_three_steps):
    if current > n:
        return 0

    if current == n:
        return 1

    ways = 0

    ways += count_ways(n, current + 1, max(0, consecutive_three_steps - 1))

    ways += count_ways(n, current + 2, max(0, consecutive_three_steps - 1))

    if consecutive_three_steps == 0:
        ways += count_ways(n, current + 3, 2)

    return ways


n = int(input())
result = count_ways(n, 0, 0)
print(result)

4
7


In [ ]:
#2651
def count_seating_arrangements(n, k, start, chosen):

    if len(chosen) == k:
        return 1

    count = 0

    for i in range(start, n):

        chosen.append(i)

        count += count_seating_arrangements(n, k, i + 1, chosen)

        chosen.pop()

    return count

n, k = map(int, input().split())
result = count_seating_arrangements(n, k, 0, [])
print(result)

4 2
3


In [ ]:
#2652
def count_seating_arrangements(n, k, start, chosen):

    if len(chosen) == k:
        return 1

    count = 0

    for i in range(start, n):
        if (i in chosen) or (i-1 in chosen) or (i+1 in chosen):
          continue

        chosen.append(i)

        count += count_seating_arrangements(n, k, i + 1, chosen)

        chosen.pop() #다른거 탐색

    return count

n, k = map(int, input().split())
result = count_seating_arrangements(n, k, 0, [])
print(result)

In [ ]:
#2624 해결 실패!
a = int(input())


10
17


[0, 2, 3, 6, 5, 11, 7, 14, 12, 17]

In [ ]:
#2625
a = int(input())
b = []
for i in range(1, a // 2 + 1):
    for j in range(1, a // 2 + 1):
        for k in range(1, a // 2 + 1):
            if i + j + k == a:
                triplet = sorted((i, j, k))
                if triplet not in b:
                    b.append(triplet)

print(len(b)) #실패! 예상 for문 범위

#########################GPT

n = int(input())
count = 0

for i in range(1, n // 2 + 1):
    for j in range(i, n // 2 + 1):
        k = n - i - j
        if k >= j and i + j > k: #k >= j 중복된 삼각형 피기
            count += 1

print(count)


78
127


In [ ]:
#2633
def find_first_position(nums, k):
    left, right = 0, len(nums) - 1
    position = len(nums) + 1

    while left <= right:
        mid = (left + right) // 2
        if nums[mid] >= k:
            position = mid + 1
            right = mid - 1
        else:
            left = mid + 1

    return position

n, k = map(int, input().split())
nums = list(map(int, input().split()))
result = find_first_position(nums, k)
print(result)

5 7
1 3 5 7 7
4


In [ ]:
#2650
a = sorted(list(map(int, input().split())))
b = [i for i in range(a[0]+1, 0, -1) if a[0] % i == 0]
for i in b:
  if a[1]%i == 0 and a[2]%i==0:
    print(i)
    break


10 20 30
10


In [ ]:
#2653

def generate_votes(n, current_vote="", b=None):
    if b is None:
        b = []

    if len(current_vote) == n:
        b.append(current_vote)
        return b

    generate_votes(n, current_vote + "O", b)
    generate_votes(n, current_vote + "X", b)

    return b


n = int(input())
a = generate_votes(n)
c = []
for i in a:
  if 'OO' not in i:
     c.append(i)

print(len(c))

3
['OXO', 'OXX', 'XOX', 'XXO', 'XXX']


In [ ]:
#2655
def binary_search(arr, target):
    left, right = 0, len(arr) - 1

    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid+1
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1

a,b = map(int, input().split())
print(f'{(b *-1)/a:.04f}')

1 5
-5.0000


In [ ]:
def find_x_intercept(a, b):
    left = -999
    right = 999
    epsilon = 1e-9

    while right - left > epsilon:
        mid = (left + right) / 2.0
        y = a * mid + b

        if abs(y) < epsilon:
            return mid

        if y > 0:
            right = mid
        else:
            left = mid

    return (left + right) / 2.0

a,b = map(int,input().split())
print(f'{find_x_intercept(a,b,list(range(-b,b+1))):.04f}')

In [46]:
#2701

a = int(input())
b = sorted(list(map(int, input().split())))

c = 501
for i in b:
  c = abs(a-i) if abs(a-i) < c else c

print(c)

437
5 21 168 202 227
210


In [49]:
#2703

a = int(input())
b = list(map(int,input().split()))

c,d = 0,0
for i in range(1,a):
  if b[i-1] < b[i]:
    c += 1
  elif b[i-1] > b[i]:
    d += 1

print(c, d)

5
3 7 5 5 6 
2 1


In [ ]:
#2733

def tomato_game(sequence):
    expected_sequence = ['t', 'm', 't', 't', 'm', 't']
    expected_index = 0

    for i, char in enumerate(sequence):
        if char != expected_sequence[expected_index]:
            if i % 2 == 0:
                return "현지인 승리"
            else:
                return "효환이 승리"

        expected_index = (expected_index + 1) % 6

    return "현지인 승리"

sequence = input().strip()
print(tomato_game(sequence))

tmttmttt
효환 승리


In [ ]:
#2733 오각형의 점의수 구하기
# 점화식  5 + (n * (n - 1) // 2) * 3 + (n - 1) * 4
n = int(input())
print(( 5 + (n * (n - 1) // 2) * 3 + (n - 1) * 4)%1000000004)


3
22


In [ ]:
#2761
a,b = map(int, input().split())
print(sorted([a+b,a-b,a*b])[1])

5 2
7


In [ ]:
#2762

a = input().split(',')

for i in a:
  print(i[0], end = '')

Changwon,Science,High,School
CSHS

In [ ]:
#2763

a,b = map(int, input().split())

f_list = [ i for i in range(1, a+1) if  a % i == 0]
sls = [i for i in f_list if b % i == 0]

print('coprime' if len(sls) == 1  else 'no')






8 11
coprime


In [ ]:
a,b = map(int, input().split())

f_list = [ i for i in range(1, a+1) if  a % i == 0]



In [ ]:
#2764
a = list(input())

for i in range(len(a)*2+1):
  print('+' if i % 2 == 0 else '-',end = '')

print(f"\n|{'|'.join(a)}|")

for i in range(len(a)*2+1):
  print('+' if i % 2 == 0 else '-',end = '')



 가나다라마바사아자차카타파하훈민정음만만세세종대왕만만세
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
| |가|나|다|라|마|바|사|아|자|차|카|타|파|하|훈|민|정|음|만|만|세|세|종|대|왕|만|만|세|
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

In [45]:
#2769
a,b,c = map(int, input().split())

print(min(a//2,b,(a+b-c)//3))

6 10 3
3


4.333333333333333

In [ ]:
#2770
def m(n, s):
    o = s.count(1)
    t = n - o # 전체중에서 차지하는 2의 개수
    c = min(o, t) #누가더 적나
    l1 = 0
    l2 = 0

    for i in range(n):
        if s[i] == 1:
            l1 += 1
        else:
            l2 += 1
        ch = (l2) + (o - l1)
        c = min(c, ch)

    return c

n = int(input())
s = [int(input()) for _ in range(n)]
print(m(n, s))



In [2]:
#2771 탐색 알고리즘 우,하 탐색

def count_paths(grid):
    n = len(grid)
    dp = [[0] * n for _ in range(n)]
    dp[0][0] = 1

    for i in range(n):
        for j in range(n):
            if dp[i][j] > 0 and grid[i][j] > 0:
                steps = grid[i][j]
                if i + steps < n:
                    dp[i + steps][j] += dp[i][j]
                if j + steps < n:
                    dp[i][j + steps] += dp[i][j]

    return dp[n-1][n-1]

N = int(input())
grid = [list(map(int, input().split())) for i in range(N)]

print(count_paths(grid))


4
2 3 3 1
1 2 1 3
1 2 3 1
3 1 1 0
3


In [ ]:
#2793
n = int(input())
tasks = [tuple(map(int, input().split())) for _ in range(n)]

tasks.sort(key=lambda x: x[1], reverse=True)

latest_start = float('inf')

for start, end in tasks:
    if latest_start > end:
        latest_start = end
    latest_start -= 1

print(latest_start+1)

4
6 7
1 4
5 5
2 6
4


In [ ]:
#2801
const_a = int(input()) * 1130
print(const_a )

In [ ]:
#2802
a,b = map(int, input().split())
print(a*b)

In [63]:
#2803 캬 지기네
import math

a,b,c = map(int, input().split())
x,y,z = map(int, input().split())

ucle = math.sqrt((a - x)**2 + (b - y)**2)

if ucle - (c+z) == 0 or ucle - (c+z) < 0:
  print('overlapped')
else:
  print('not overlapped')

1 1 1
3 3 2
overlapped


In [ ]:
#3001
a = input()
b = list(map(int, input().split()))
c = int(input())
print(b.index(c)+1 if c in b else -1)

10
2 3 7 4 9 10 223 111 23 39
111
7


In [ ]:
#3002
def binary_search(arr, target):
    left, right = 0, len(arr) - 1

    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid+1
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1


a = int(input())
b = list(map(int, input().split()))
c = int(input())
d = list(map(int, input().split()))

for i in d:
  print(binary_search(b,i), end = ' ')

5
2 23 55 87 100
4
5 2 100 55
-1
0
4
2


In [ ]:
#3003
#include <iostream>
#include <vector>

# using namespace std;

# int main() {
#     ios_base::sync_with_stdio(false);
#     cin.tie(NULL);

#     int num;
#     vector<int> numbers;
#     int count = 0;

#     while (cin >> num) {
#         count++;
#         if (count % 50 == 0) {
#             cout << num << ' ';
#         }
#     }

#     cout << '\n';
#     return 0;
# }


In [ ]:
#3004
a = input()
b = list(map(int, input().split()))
c = dict((j, i) for i, j in enumerate(sorted(b)))
print(*[c[i] for i in b])

5
50 23 54 24 123 
2 0 3 1 4


In [61]:
#3005
import math
from functools import reduce

def lcm(a, b):
    return abs(a * b) // math.gcd(a, b)

def lcm_multiple(numbers):
    return reduce(lcm, numbers)

n = int(input())
numbers = list(map(int, input().split()))

result = lcm_multiple(numbers)
print(result)

42
12 11 5 6 5 7 7 11 9 6 6 2 4 2 12 8 3 4 1 4 1 3 10 5 11 10 9 3 12 12 7 12 7 10 5 12 8 8 7 12 4 3 
27720


In [62]:
#reduce 예시
def lcm(a, b):
    return a+b

def lcm_multiple(numbers):
    return reduce(lcm, numbers)

numbers = list(map(int, input().split()))

result = lcm_multiple(numbers)
print(result)

1 2 3
6


In [52]:
#3006
for _ in range(int(input())):
    a = int(input())
    b = int(a**0.5)

    if b * b == a:
        print(a)
    else:
        print(b * b if b * b <= a else (b - 1) * (b - 1))




2
10
9
100000000
100000000


In [51]:
int(10**0.5)

3

In [42]:
#3007

a, b = map(int, input().split())
c = list(map(int, input().split()))

# 구간 합 배열 생성 #sum보다는 구간합 구하는게 복잡도가 낮음
prefix_sum = [0] * (a + 1)
for i in range(1, a + 1):
    prefix_sum[i] = prefix_sum[i - 1] + c[i - 1]

# 각 쿼리에 대해 결과 출력
for _ in range(b):
    d, e = map(int, input().split())
    print(prefix_sum[e] - prefix_sum[d - 1])


6 3
3 5 2 1 4 3 
2 4
8
1 1
3
1 3
10


In [39]:
#3008
def cnt_sub(arr, tgt, idx, csum, sub):
    if csum == tgt and len(sub) == 7:
        return sub

    if idx >= len(arr):
        return None

    result = cnt_sub(arr, tgt, idx + 1, csum, sub)
    if result:
        return result

    result = cnt_sub(arr, tgt, idx + 1, csum + arr[idx], sub + [arr[idx]])
    if result:
        return result

    return None

a = sorted([int(input()) for i in range(9)])
result = cnt_sub(a, 100, 0, 0, [])

if result:
    for i in result:
        print(i)


20
7
23
19
10
15
25
8
13
7
8
10
13
19
20
23


In [32]:
#3009

def cnt_sub(arr, tgt, idx, csum):
    global cnt
    if idx == len(arr):
        if csum == tgt:
            cnt += 1
        return

    cnt_sub(arr, tgt, idx + 1, csum)
    cnt_sub(arr, tgt, idx + 1, csum + arr[idx])

n, s = map(int, input().split())
arr = list(map(int, input().split()))

cnt = 0
cnt_sub(arr, s, 0, 0)

if s == 0:
    cnt -= 1

print(cnt)



5 0
-7 -3 -2 5 8
1


In [ ]:
#3011
def bubbleSort(x):
    length = len(x) - 1
    b = x[:]
    a = 0
    for i in range(length):
        a += 1
        for j in range(length - i):
            if x[j] > x[j + 1]:
                x[j], x[j + 1] = x[j + 1], x[j]
        if b == x:
            return a - 1
        b = x[:]
    return a

a = input()
arr = list(map(int, input().split()))

print(bubbleSort(arr))

5
10 50 30 20 40


2

In [ ]:
# #3014
# #include <stdio.h>

# int partition(int arr[], int low, int high) {
#     int pivot = arr[high];
#     int i = (low - 1);

#     for (int j = low; j < high; j++) {
#         if (arr[j] < pivot) {
#             i++;
#             int temp = arr[i];
#             arr[i] = arr[j];
#             arr[j] = temp;
#         }
#     }

#     int temp = arr[i + 1];
#     arr[i + 1] = arr[high];
#     arr[high] = temp;

#     return (i + 1);
# }

# void quick_process(int arr[], int low, int high) {
#     if (low < high) {
#         int pi = partition(arr, low, high);

#         quick_process(arr, low, pi - 1);
#         quick_process(arr, pi + 1, high);
#     }
# }

# int main() {
#     int n;
#     scanf("%d", &n);
#     int arr[n];

#     for (int i = 0; i < n; i++) {
#         scanf("%d", &arr[i]);
#     }

#     quick_process(arr, 0, n - 1);

#     for (int i = 0; i < n; i++) {
#         printf("%d ", arr[i]);
#     }

#     return 0;
# }



5
2 6 4 8 6
[2, 4, 6, 6, 8]


In [ ]:
#3015
a,b = map(int, input().split())
d = sorted(list((i,int(j)) for i,j in [list(map(str, input().split())) for i in range(a)]), key = lambda x : x[1], reverse=True)

for i,j in d[:b]:
  print(i)

4 2
Jeon 95
Kim 59
Lee 90
Bae 100
Bae
Jeon


In [ ]:
#3016
a = int(input())
b = [list(enumerate(map(str, input().split()))) for i in range(a)] #점수 리스트

c = max(b, key=lambda x: int(x[1][1])) #첫번째 과목의 점수가 가장 높은 학생

d = sorted([int(j) for i in b for k,j in i if k == 2]) #2번째 정렬
e = sorted([int(j) for i in b for k,j in i if k == 3]) #3번쨰 정렬

print(c[0][1], d[::-1].index(int(c[2][1]))+1 , e[::-1].index(int(c[3][1]))+1) #뒤에서 부터 인덱스를 검사해 중복일 경우 맨뒤에 번호

4
Jeon 95 100 100
Kim 59 100 80
Lee 90 100 80
Bae 100 82 80
Bae 4 2


In [ ]:
#3017
a =[list(map(int, input().split())) for i in range(int(input()))]

b = []
for i,j in enumerate(a):
  b.append([i+1, *j])

b.sort(key=lambda x: (-x[1], -x[2], x[0]))

for i in b:
  print(*i)


5
100 90
90 100
80 80
80 90
60 50
1 100 90
2 90 100
4 80 90
3 80 80
5 60 50


In [ ]:
a = int(input())
b = [list(map(str, input().split())) for i in range(a)]
c = max(b, key=lambda x: max(map(int, x[1])))


In [65]:
#3019

a = int(input())
b = [input().split() for i in range(a)]
c = sorted(b, key = lambda x : (int(x[1]),int(x[2]),int(x[3]), x[0]))

for i in c:
  print(i[0])

20
sleepa 2014 05 23
golfb 2014 06 02
traveljp 2015 11 22
basketball 2013 02 01
studyabc 2014 05 23
sleepk 201 05 23


KeyboardInterrupt: Interrupted by user

In [ ]:
#3021
a = int(input())
b = int(input())
print(a+b)

In [ ]:
#3090
a = int(input())
b = [i for i in range(1,int(input()))]
print(b[-1])

3
7
6


In [ ]:
#3110 (큐)
from collections import deque as d

n,k=map(int,input().split())
q=d(range(1,n+1))

q.popleft() #첫번째값 삭제  FIFO(First In, First Out)
while len(q)>1:q.rotate(-((k-1)%len(q)));q.popleft()

print(q[0])

In [ ]:
#3120 그리디 알고리즘
a,b=map(int,input().split())
arr=[0,1,2,3,2,1,2,3,3,2]

print(abs(b-a)//10 + arr[abs(b-a)%10])

22 3
3


In [ ]:
#3129 스택 기본 문제

def check_parentheses(s):
    stack = []

    for char in s:
        if char == '(':
            stack.append(char)
        elif char == ')':
            if not stack:
                return "bad"
            stack.pop()

    if not stack:
        return "good"
    else:
        return "bad"


s = input()
print(check_parentheses(s))

((((((()(())(()()))))(()(()(())))()()))()))()(()()
bad


In [ ]:
#3301

a = int(input())
b = [50000, 10000,5000,1000,500,100,50,10]

c = 0
for i in b:
  c += a//i
  a %= i

print(c)

54520
8


In [ ]:
#3440

def generate_votes(n,m, current_vote=""):
    if len(current_vote) == n:
        if current_vote.count('1') == m:
            print(current_vote, end = ' ')
        return

    generate_votes(n,m, current_vote + "0")

    generate_votes(n,m, current_vote + "1")


n,m = map(int, input().split())
generate_votes(n,m)

3 2

0
00
000
001
01
010
011
011 1
10
100
101
101 11
110
110 111


In [ ]:
#3701
import math

a = int(input())

b = [[] for i in range(a)]

for i in range(0, a):
  for j in range(i+1):
    b[i].append(math.comb(i,j))

for i in b:
  print(*i)

5
1
1 1
1 2 1
1 3 3 1
1 4 6 4 1


In [ ]:
#3702

def pasc_val(r, c):
    MOD = 100000000
    size = r + c - 1
    pasc = [[0] * (size + 1) for _ in range(size + 1)]
    for i in range(size + 1):
        pasc[i][0] = 1
        pasc[i][i] = 1

    for i in range(2, size + 1):
        for j in range(1, i):
            pasc[i][j] = (pasc[i-1][j-1] + pasc[i-1][j]) % MOD

    return pasc[r+c-2][c-1]

r, c = map(int, input().split())
print(pasc_val(r, c))

3 2
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
3


In [ ]:
#3704 (점화식:f(n)=f(n−1)+f(n−2)+f(n−3))

def count_ways(n):
    dp = [1]+[1]+[2]+[4]+([0] * (n + 1))
    if n == 0:
        return dp[0]
    elif n == 1:
        return dp[1]
    elif n == 2:
        return dp[2]
    elif n == 3:
        return dp[3]

    for i in range(4, n + 1):
        dp[i] = (dp[i-1] + dp[i-2] + dp[i-3]) % 1000

    return dp[n]

n = int(input())

print(count_ways(n))


5
13


In [ ]:
#3709
import sys

sys.setrecursionlimit(1000000)
n = int(input())

DIV = 100000007

dp = [0] * (n + 1)

dp[1] = 1
if n > 1:
    dp[2] = 3

for i in range(3, n + 1):
    dp[i] = (dp[i-1] + 2 * dp[i-2]) % DIV


print(dp[n])



1
0


In [ ]:
#3712 점화
n = int(input())

if n % 3 == 0:
    n //= 3
    res = 1
    for _ in range(n):
        res *= 2
        res %= 100000007
    print(res)
else:
    print(0)

n=int(input())
print(pow(2,n//3,100000007)*(n%3<1))

In [41]:
#3713

import sys

sys.setrecursionlimit(1000000)
n = int(input())

MOD = 100007

# DP 배열 초기화
arr = [0] * (n + 1)
arr[0] = 1
arr[1] = 3

# 점화식 적용
for i in range(2, n):
    arr[i] = arr[i-1] + 2 * arr[i-2]
    arr[i] %= MOD

# 결과 출력
print(arr[n-1])


2
3


In [ ]:
#3117
a = int(input())

b = []
for i in range(a):
  c = int(input())
  if len(b) == 0 and c ==0:
    pass
  elif c != 0:
    b.append(c)
  elif c == 0:
    del b[-1]

print(sum(b))

10
1
3
5
4
0
0
7
0
0
6
7


In [ ]:
#4011
a = input()
b = '20' + a[0:2] if int(a[7]) > 2 else '19' + a[0:2]
print(f"{b}/{a[2:4]}/{a[4:6]} {'F' if int(a[7]) % 2 == 0 else 'M'}")

781201-1273845
1978/12/01/ M


In [ ]:
#4012
a = input()
b =list(map(int, input().split()))
c = sorted(b, reverse=True)
for i in b:
  print(i, c.index(i)+1)

10
60 34 55 100 90 76 60 90 80 87
60 7
34 10
55 9
100 1
90 2
76 6
60 7
90 2
80 5
87 4


In [ ]:
#4013
a = int(input())

print(f'2 {bin(a)[2:]}')
print(f'8 {oct(a)[2:]}')
print(f'16 {hex(a)[2:].upper() if a < 32767 else ""}')



15
2 1111
8 17
16 F


In [ ]:
#4019
a  = int(input())
b = list(map(int, input().split()))
c = 0
while True:


8
5 7 10 1 2 10 11 6
38


In [ ]:
#4026
a = sorted(list(map(int, input().split())))
mid = len(a)//2
print(a[mid] if len(a) % 2 != 0 else ( a[mid-1] + a[mid]) / 2)

58 35 77 59 68
59


In [ ]:
#4031
a = list(map(int, input().split()))

b = [i for i in a if i % 2 == 0] + [0]
c = [i for i in a if i % 2 != 0] + [0]

print(max(b)+max(c))

1 1 1 1
1


In [ ]:
#4036
n = int(input())
m = int(input())
print(f'{(n + m) // 2}\n{(n - m) // 2}')

1998
0


[]

In [9]:
#4037
n = int(input())

a,i = [], 2
while n > 1 :
  if n % i == 0:
    a.append(i)
    n = n//i
  else:
    i += 1

print(*a)

72
2 2 2 3 3


In [ ]:
#4038 이해 못함
import math

def heron_area(x1, y1, x2, y2, x3, y3):
    a = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    b = math.sqrt((x3 - x2) ** 2 + (y3 - y2) ** 2)
    c = math.sqrt((x1 - x3) ** 2 + (y1 - y3) ** 2)
    s = (a + b + c) / 2
    return math.sqrt(s * (s - a) * (s - b) * (s - c))

def intersection(x1, y1, x2, y2):
    if y1 * y2 < 0:  # 두 점이 수면을 기준으로 다른 쪽에 있을 때
        return x1 - y1 * (x2 - x1) / (y2 - y1), 0
    return None

def calculate_area_above_surface(x1, y1, x2, y2, x3, y3):
    points = []
    if y1 > 0:
        points.append((x1, y1))
    if y2 > 0:
        points.append((x2, y2))
    if y3 > 0:
        points.append((x3, y3))

    i1 = intersection(x1, y1, x2, y2)
    if i1:
        points.append(i1)

    i2 = intersection(x2, y2, x3, y3)
    if i2:
        points.append(i2)

    i3 = intersection(x3, y3, x1, y1)
    if i3:
        points.append(i3)

    if len(points) < 3:
        return 0

    points = sorted(points, key=lambda p: (p[0], p[1]))  # 점들을 정렬
    area = heron_area(points[0][0], points[0][1], points[1][0], points[1][1], points[2][0], points[2][1])

    return round(area)

# 입력 받기
x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())
x3, y3 = map(int, input().split())

# 결과 출력
print(calculate_area_above_surface(x1, y1, x2, y2, x3, y3))

-4 -1
6 -3
3 6
[(-3.0, 0), (3, 6), (5.0, 0)]
24


In [ ]:
#4041
a = list(input())
print(f'{int("".join(a[::-1]))}\n{sum(map(int,a))}')

#####################GPT

a = input()[::-1]
print(f'{int(a)}\n{sum(map(int,a[::-1]))}')

320
23
5


In [ ]:
#4045
def count_ways(n, m):
    print(n,m)
    if n == 0:
        return 1
    if n < 0 or m == 0:
        return 0
    return count_ways(n, m - 1) + count_ways(n - m, m)  # m명을 포함하지 않는 경우 + m명을 포함하는 경우

n, m = map(int, input().split())
print(count_ways(n, m))

In [ ]:
a = list(input())[::-1]
b = [bin(ord(i))[2:] for i in a]

c = [[] for _ in range(len(b))]

for i in range(len(b)):
    for bit in b[i]:
        if bit == '1':
            c[i].append('0')
        else:
            c[i].append('1')

for i in c:
  print(''.join(i))

test
0001011
0001100
0011010
0001011


In [ ]:
#4051

a = [list(map(float, input().split())) for i in range(5)]

b = 0
for i, j in a:
    o = min((j - i) - 1, 4)
    b += max(0, o)

t = 10000 * b
if b >= 15:
    t -= int(t * 0.05)
elif b <= 5:
    t += int(t * 0.05)

print(int(t))

16.0 21.0
16.5 21.5
17.5 21.5
19.5 24.0
22.5 24.0
15.0
142500


In [ ]:
15.5

(2000.0, 40000)

In [ ]:
#4056

a = int(input())

if 500 >= a:
  print(int(a*(70/100)))
elif 500 < a <= 1500:
  print(int(350+(a-500)*40/100))
elif 1500 < a <= 4500:
  print(int(750 + (a-1500)*15/100))
elif 4500 < a <= 10000:
  print(int(1200 + (a - 4500)*5/100))
elif 10000 < a:
  print(int(1475 + (a - 10000)*2/100))



1500
750


In [ ]:
#4085
m, n, x, y = map(int, input().split())
matrix = [list(map(int, input().split())) for _ in range(n)]

max_fertility = 0

for i in range(n):
    for j in range(m):
        if i + y <= n and j + x <= m:
            current_fertility = sum(matrix[i+a][j+b] for a in range(y) for b in range(x))
            max_fertility = max(max_fertility, current_fertility)

print(max_fertility)


10 3 2 2
10 15 11 24 55 21 10 19 14 10
10 12 19 19 44 39 24 15 14 11
10 77 66 50 50 50 40 35 25 15
183


In [ ]:
#4506

a,b = map(int, input().split())

for i in range(min(a,b), 0,-1):
  if a%i==0 and b%i==0 :
    print(i)
    c = i
    break

d = min(a,b)
while True:
  if d%a==0 and d%b==0 :
    print(d)
    break
  d+=c

24 18
6
72


In [ ]:
#4506
a = [int(input()) for i in range(9)]
b = max([(i+1,j) for i,j in enumerate(a)], key=lambda x: x[1])
print(f'{b[1]}\n{b[0]}')

In [ ]:
#4531
a = [int(input()) for i in range(5)]
print(f'{sum(a)//5}\n{sorted(a)[2]}')

10
40
30
60
30
170
30


In [ ]:
#4532
a = int(input())
b = [int(i) for i in input()]

for i in range(len(b)):
  print(a*b[-(i+1)])
  b[-(i+1)] = int(str(a*b[-(i+1)]) + ('0'*i))

print(sum(b))



472
385
2360
3776
1416
181720


In [ ]:
#4536
a = [int(input()) for i in range(10)]
b = [(a.count(i), i) for i in set(a)]
print(sum(a)//10)
print(max(b, key=lambda x: x[0])[1])

10
40
30
60
30
20
60
30
0
50
33
30


In [ ]:
#4536
def sieve_of_eratosthenes(limit):
    is_prime = [True] * (limit + 1)
    is_prime[0] = is_prime[1] = False
    p = 2
    while (p * p <= limit):
        if is_prime[p]:
            for i in range(p * p, limit + 1, p):
                is_prime[i] = False
        p += 1
    return is_prime

def find_twin_primes(a, b):
    primes = sieve_of_eratosthenes(b)
    twin_primes = []

    for i in range(max(a, 2), b + 1):
        if primes[i]:
            twin_primes.append(i)

    return twin_primes

a = int(input())
b = int(input())

tw = find_twin_primes(a, b)

print(f'{sum(tw)}\n{tw[0]}' if len(tw) != 0 else -1)



1
500
21536
2


In [ ]:
#4546
import itertools

def sjs(arr):
    cmb = itertools.combinations(arr, 3)
    max_dgt = -1

    for c in cmb:
        cur_sum = str(sum(c))
        dgt = int(cur_sum[-1] )
        if dgt > max_dgt:
            max_dgt = dgt
    return max_dgt

b = reversed([(i, sjs(list(map(int, input().split())))) for i in range(1, int(input())+1)])
print(max(b, key=lambda x: x[1])[0])

3
7 5 5 4 9
1 1 1 1 1
2 3 3 2 10
1


In [ ]:
#4561



In [ ]:
#4561

a = [int(input()) for i in range(7)]
b =sorted([i for i in a if i % 2 != 0]) + [0]
print(f'{sum(b)}\n{b[0]}' if sum(b) != 0 else -1)

2
4
6
3
2
2
10
-1


In [ ]:
#4592
matr = [[0 for i in range(100)] for i in range(100)]

a = int(input())
b = [list(map(int, input().split())) for i in range(a)]

for i,j in b:
  for k in range(10):
    for n in range(10):
      matr[-(j+n)][i+k-1] = 1

area = 0
for i in matr:
  area += sum(i)

print(area)

In [ ]:
#4596
a = [list(map(int, input().split())) for _ in range(9)]
b = max([max(row) for row in a])

for i in range(9):
    if b in a[i]:
      print(f'{b}\n{i+1} {a[i].index(b)+1}')
      break


In [ ]:
#4621
n,k = map(int, input().split()); a = [i for i in range(1,n+1) if n%i==0]
print(a[k-1] if k < len(a) else 0)

1234 6
0


In [ ]:
#4626
a = int(input())
b = list(map(int, input().split()))
cg = 0
sh = 0
for i in b:
  if i == 0:
    sh = 0
  else:
    sh+=1
    cg += sh

print(cg)

10
1 0 1 1 1 0 0 1 1 0
10


In [ ]:
#4651
for i in [map(int, input().split()) for i in range(3)]:
  b = ''.join(map(str, i)).count('1') #등
  print('A' if b == 3 else 'B' if b ==2 else 'C' if b == 1 else 'D' if b ==0 else 'E')

0 1 0 1
1 1 1 0
0 0 1 1
2
3
2


In [ ]:
#4681
a = list(map(int, input().split()))
b = sum([i**2 for i in a])
print(b%10)

0 4 2 5 6
1


In [ ]:
#4711
a = [map(int, input().split()) for i in range(4)]

hs = 0
b = []
for i,j in a:
  hs += j
  hs -= i
  if hs > 10000:
    hs = 10000
  b.append(hs)

print(max(b))
##########################GPT(요청)
a = [map(int, input().split()) for i in range(4)]
hs = 0
b = [(hs := min(hs + j - i, 10000)) for i, j in a]
print(max(b))

0 32
3 13
28 25
39 0
84


In [ ]:
#4716
a = [map(int, input().split()) for i in range(10)]
hs = 0
b = [(hs := min(hs + j - i, 10000)) for i, j in a]
print(max(b))

In [ ]:
#4741

a,b = map(int, input().split())
c = int(input())

d = []
for i in [3600, 60]:
  d.append(c//i)
  c %= i


print((a+d[0]+1)%24 if d[1]+b > 60 else (a+d[0])%24, b+d[1]-60 if d[1]+b > 60 else b+d[1])


14 0
786
3 6


In [ ]:
#4746
a,b,c = map(int, input().split())
secc = int(input())

d = []
for i in [3600, 60,1]:
    d.append(secc//i)
    secc %= i

if d[2]+c > 60:
  b+=1

print((a+d[0]+1)%24 if d[1]+b > 60 else (a+d[0])%24, b+d[1]-60 if d[1]+b > 60 else b+d[1], c+d[2]-60 if d[2]+c > 60 else c+d[2] )

KeyboardInterrupt: Interrupted by user

In [ ]:
#4751
a = sorted([list(map(int,input().split())) for i in range(int(input()))], key = lambda x : x[2], reverse = True)

b, c = [], 0
for i in a:
  if c == 3:
    break

  if b.count(i[0]) != 2:
    print(i[0], i[1])
    b.append(i[0])
    c += 1

4
1 1 230
1 2 210
1 3 205
3 4 190
1 1
1 2
3 4


In [ ]:
a = sorted([list(map(int,input().split())) for i in range(int(input()))], key = lambda x : x[2], reverse = True)

print(a[0][0], a[0][1])
print(a[1][0], a[1][1])

if a[0][0] != a[1][0]:
  print(a[2][0], a[2][1])
else:
  for i in a[2:]:
    if i[0] != a[0][0]:
      print(i[0], i[1])
      break



In [ ]:
#4771
a = list(input())
b = 10
for i in range(1,len(a)):
  if a[i-1] != a[i]:
    b+=10
  else:
    b+=5

print(b)

()()()))(
80


In [ ]:
#4776

A = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
B = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']

year = int(input())

print(f"{B[(year + 8) % 12]}{A[(year + 6) % 10]}")

In [ ]:
#4781
a,b = map(int, input().split())
board = [list(map(int, input().split())) for i in range(b)]


from collections import deque


n = len(board)
m = len(board[0])

dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]

queue = deque()

for i in range(n):
    for j in range(m):
        if board[i][j] == 1:
            queue.append((i, j))

steps = 0

while queue:
    for _ in range(len(queue)):
        x, y = queue.popleft()

        for i in range(4):
            nx, ny = x + dx[i], y + dy[i]

            if 0 <= nx < n and 0 <= ny < m and board[nx][ny] == 0:
                board[nx][ny] = 1
                queue.append((nx, ny))

    steps += 1

for row in board:
    if 0 in row:
        print(-1)
        break
else:
    print(steps - 1)

5 3
0 -1 0 0 0 
-1 -1 0 1 1
0 0 0 1 1
-1


In [3]:
#4801

a,b,c = map(int, input().split())
print(max(0,(a*b)-c))

250 2 140
360


In [ ]:
#4816
a = int(input())
c = []
for i in [300,60,10]:
  c.append(a//i)
  a %= i

print(' '.join(map(str, c)) if a == 0 else -1)

9840
32 4 0


In [ ]:
#4831
a = int(input())
b = list(map(int, input().split()))
print(b.count(a))

1
2 3 4
0


In [ ]:
#4846
print(sum([j%i for i,j in [list(map(int, input().split())) for i in range(int(input()))]]))

5
24 52
13 22
5 53
23 10
7 70
[4, 9, 3, 10, 0]
26


In [ ]:
#4891
a = input()
b = list(map(int, input().split()))
print(max(b)-min(b))

5
27 35 92 75 42
65


In [ ]:
#4991

a = [int(input()) for i in range(int(input()))]

mxc, vis = 0,0
for i in reversed(a):
  if i > mxc:
    mxc = i
    vis +=1

print(vis)

10
3
4
5
5
4
1
2
3
4
1
3


In [ ]:
#5078

a = [int(input()) for i in range(3)]

if sum(a) > 180 or 180 > sum(a):
  print('Error')
elif a[0] == a[1] == a[2]:
  print('Equilateral')
elif a[0] == a[1] or a[1] == a[2] or a[2] == a[0]:
  print('Isosceles')
else:
  print('Scalene')


In [ ]:
 #5080
a, b = 100, 100
c = [list(map(int, input().split())) for i in range(int(input()))]

for i in c:
  if i[0] > i[1]:
    b -= i[0]
  elif i[0] < i[1]:
    a -= i[1]

print(a)
print(b)

4
5 6
6 6
4 3
5 2
94
91


In [ ]:
#5123
import itertools

a = int(input())*0
b = list(map(int, input().split()))

for i in itertools.combinations(b,2):
  if sum(i) % 3 == 0:
    a += 1

print(a)


5
1 4 2  3 3
(1, 2)
(4, 2)
(3, 3)
3


In [ ]:
from collections import Counter

c = input()
b = list(map(int, input().split()))
#Counter 조건넣어주고 이에 맞게 딕셔너리로 나눠줌 나머지로 나눔

mod_count = Counter(x % 3 for x in b) #b원소중 3으로 나누어 지는거 찾
print(mod_count)

#3으로 나누었을 때 나머지가 같은 것끼리의 쌍을 계산
a = (mod_count[0] * (mod_count[0] - 1) // 2) + (mod_count[1] * mod_count[2])

print(a)

5
1 4 2 2 3
Counter({1: 2, 2: 2, 0: 1})
4


In [ ]:
a = int(input())
b = int(input())
c = int(input())

if a + b + c == 180:
  if a == b == c == 60:
    print("Equilateral")
  elif a + b + c == 180 and (a == b or b == c or c == a):
    print("Isosceles")
  else:
    print("Scalene")
else:
  print("Error")


In [ ]:
#2030
a = [['.'] * 60 for _ in range(30)]

for _ in range(int(input())):
    cmd = input().split()
    name, x1, y1, x2, y2 = cmd[0], int(cmd[1]) - 1, int(cmd[2]) - 1, int(cmd[3]) - 1, int(cmd[4]) - 1

    # 윈도우 상단 테두리
    a[y1][x1] = '+'
    for j in range(x1 + 1, min(x2, x1 + len(name) + 1)):
        a[y1][j] = name[j - x1 - 1]
    for j in range(x1 + len(name) + 1, x2):
        a[y1][j] = '-'
    a[y1][x2] = '+'

    # 윈도우 중간 부분
    for i in range(y1 + 1, y2):
        a[i][x1] = '|'
        for j in range(x1 + 1, x2):
            a[i][j] = ' '
        a[i][x2] = '|'

    # 윈도우 하단 테두리
    a[y2][x1] = '+'
    for j in range(x1 + 1, x2):
        a[y2][j] = '-'
    a[y2][x2] = '+'

# 결과 출력
for row in a:
    print("".join(row))






1
ie9 2 3 15 6
............................................................
............................................................
.+ie9---------+.............................................
.|            |.............................................
.|            |.............................................
.+------------+.............................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
.........

In [ ]:
#2044
a = input()
a = list(a[a.rfind('C') + 1:])

while 'A' in a or 'B' in a:
    if 'B' in a and a.index('B') <= a.index('A'):
        idx = a.index('B')
        del a[idx-2:idx+1]
    elif 'A' in a:
        idx = a.index('A')
        del a[idx-1:idx+1]

print("".join(a))

011B1C11A122B11A
111


In [ ]:
# 2081
a = [input() for i in range(9)]
b = [(i+1,j) for i,j in enumerate(a)]
c = max(b, key=lambda x: x[1])
print(f'{c[1]}\n{c[0]}')

1
9
9
2


In [ ]:
n,k = map(int, input().split())
c = list(map(int, input().split()))
print(c.index(k)+1 if k in c else -1)

5 3
5 2 9 7 3
5


In [ ]:
a,b,c,d = map(int, input().split())

e = [a] #시작값
for i in range(1,d):
  e.append(e[i-1]*b+c)

print(e[d-1])

1 -2 1 8
-85


In [ ]:
from math import comb

def solve(n, m, k, p):
    abs_n = abs(n)
    abs_m = abs(m)

    if n == 0 or m == 0: #특수경

        total_distance = abs_n + abs_m + 2

        total_paths = comb(total_distance, 2)

        if n == 0:
            extra_turns = abs_m
        else:
            extra_turns = abs_n

        if k == 0:
            valid_paths = total_paths - 2 + extra_turns
        else:
            valid_paths = total_paths - 3 + extra_turns
    else: #일반
        total_distance = abs_n + abs_m
        total_paths = comb(total_distance, abs_n)


        if k == 1:
            valid_paths = total_paths - 3
        else:
            valid_paths = total_paths - 2

    if valid_paths < 0:
        valid_paths = 0

    if p > 0:
        valid_paths = valid_paths % p

    return total_distance, valid_paths

n, m, k, p = map(int, input().split())
distance, num_paths = solve(n, m, k, p)
print(distance, num_paths)


-18 0 1 277
20 205


In [ ]:
from math import comb

def solve(n, m, k, p):
    abs_n = abs(n)
    abs_m = abs(m)

    if n == 0 or m == 0:  # 특수 경로: 직선 경로

        total_distance = abs_n + abs_m + 2

        total_paths = comb(total_distance, 2)

        if n == 0:
            extra_turns = abs_m
        else:
            extra_turns = abs_n

        if k == 0:
            valid_paths = total_paths - 2 + extra_turns
        else:
            valid_paths = total_paths - 3 + extra_turns
    else: #일반일때
        total_distance = abs_n + abs_m
        total_paths = comb(total_distance, abs_n)


        if k == 1:
            valid_paths = total_paths - 3
        else:
            valid_paths = total_paths - 2

    if valid_paths < 0:
        valid_paths = 0

    if p > 0:
        valid_paths = valid_paths % p

    return total_distance, valid_paths

n, m, k, p = map(int, input().split())
distance, num_paths = solve(n, m, k, p)
print(distance, num_paths)


-18 0 1 277
20 151


65


495

In [ ]:
#6101
import numpy as np
print('1.24.3')
a =np.zeros(10)
print(a)
a[4] = 1
print(a)

1.24.3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#6102
import numpy as np
print(np.arange(10, 50))
print(np.arange(49,9,-1))
print(np.arange(0, 9).reshape(3,3))
print((np.nonzero([1,2,0,0,4,0])))
print(np.eye(3,3))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4]),)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#6103
import numpy as np

np.random.seed(32)

array_3x3x3 = np.random.random((3, 3, 3))
print(array_3x3x3)

array_10x10 = np.random.random((10, 10))
min_value = array_10x10.min()
max_value = array_10x10.max()
print(f"{min_value} {max_value}")

array_30 = np.random.random(30)
mean_value = array_30.mean()
print(mean_value)

In [ ]:
import numpy as np

array_10x10_border = np.ones((10, 10))
array_10x10_border[1:-1, 1:-1] = 0
print(array_10x10_border)

checkerboard_8x8 = np.zeros((8, 8), dtype=int) # dtype이 있냐에 따라서 숫자뒤 . 여부
checkerboard_8x8[1::2, ::2] = 1
checkerboard_8x8[::2, 1::2] = 1
print(checkerboard_8x8)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#6130
a = input()
b = int(a[:a.find('x')])
c = int(a[a.find('x')+2:])

print(f"{(c/b) if a[a.find('x')+1] == '+' else -(c/b):.02f}")

5x+4
-0.80


In [ ]:
#6131
a = input()
b =int(a[a.find('x')+2:a.find('=')])
c = int(a[a.find('=')+1:])
d = b+c if a[a.find('x')+1] == '-' else c-b

print(f"{d/int(a[:a.find('x')]):.02f}")

4x-3=2
1.25


In [ ]:
5/4

1.25